config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :users
  
  resources :index,  only: [:index]
  resources :painel,  only: [:index]
  resources :loans, only: [:new, :show, :index]
  resources :loan_applicants, only: [:new, :create]
  resources :simulate_loan,  only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :loan_applicant
  validates :zip_code, :state, :city, :street, :loan_applicant, presence: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
  has_many :loan_applicants
  has_many :loan_installments
  validates :amount, :installments, :monthly_rate, numericality: {greater_than: 0}, presence: true
  validates :date_acquisition, presence: true
  before_validation :set_date_acquisition
  after_initialize :set_default
  
  private
  def set_default
    self.monthly_rate = 0.015
  end
  def set_date_acquisition
    self.date_acquisition = Time.zone.now
  end
  
end

app/models/loan_applicant.rb
class LoanApplicant < ApplicationRecord
  belongs_to :loan
  has_many :addresses
  accepts_nested_attributes_for :loan
  accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true
  validates :company_name, :cnpj, :phones, :loan, :addresses, presence: true
  has_many :loan_installments
end

app/models/loan_installment.rb
class LoanInstallment < ApplicationRecord
  belongs_to :loan
  belongs_to :loan_applicant
  validates :value,:installment_number,:due_date, :loan, :loan_applicant, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  def after_sign_in_path_for(resource)
    painel_index_path 
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/loan_applicants_controller.rb
class LoanApplicantsController < AuthenticatedController
  def new
    @loan = Loan.new(loan_params)
    @loan_applicant = LoanApplicant.new(loan: @loan)
    unless @loan.amount && @loan.installments
      redirect_to new_loan_path
    end
  end

  def create
    if params[:loan_applicant][:loan_attributes].present? && params[:loan_applicant][:loan_attributes][:id].present?
      @loan_applicant = LoanApplicant.new(company_name: params[:loan_applicant][:company_name],cnpj: params[:loan_applicant][:cnpj],phones: params[:loan_applicant][:phones])
      loan = Loan.find(params[:loan_applicant][:loan_attributes][:id])
      @loan_applicant.loan = loan
    else
      @loan_applicant = LoanApplicant.new(loan_applicant_params)
    end
    @loan_applicant.phones = @loan_applicant.phones.reject{|p| p.empty? }
    respond_to do |format|
      if @loan_applicant.save
        generate_first_loan_installmenent
        if params[:new_loan_applicant] == 'true'
          @loan_applicant = LoanApplicant.new(loan: @loan_applicant.loan)
          format.html { render :new, locals: {loan_applicant: @loan_applicant, loan: @loan_applicant.loan} }
        else   
          format.html { redirect_to painel_index_path, notice: "created." }
        end
      else
        @loan_applicant = LoanApplicant.new(loan: @loan_applicant.loan)
        format.html { render :new, locals: {loan_applicant: @loan_applicant, loan: @loan_applicant.loan} }
      end
    end
  end
  
  private 
  def loan_applicant_params
    params.require(:loan_applicant).permit(
      :company_name,
      :cnpj,
      phones: [],
      loan_attributes:[
        :id,
        :amount,
        :installments,
      ],
      addresses_attributes:[
        :zip_code,
        :state,
        :city,
        :street,
        :number,
        :_destroy
      ]
    )
  end

  def loan_params
    params.permit(:amount,:installments)
  end

  def generate_first_loan_installmenent
    loan = @loan_applicant.loan
    value = helpers.loan_calculation_per_applicant(loan)
    LoanInstallment.create(value: value, due_date: (loan.date_acquisition + 1.month), installment_number: 1, loan: loan, loan_applicant: @loan_applicant)
  end
end

app/controllers/loans_controller.rb
class LoansController < AuthenticatedController
  before_action :set_loan, only: [:show]
  
  def index
    @loans = Loan.all
  end
  
  def new
    @loan = Loan.new
  end
  
  def show
  end

  private
  def set_loan
    @loan = Loan.find(params[:id])
  end
end

app/controllers/painel_controller.rb
class PainelController < AuthenticatedController
  def index
    @loans = Loan.last(5).reverse
  end
end

app/controllers/simulate_loan_controller.rb
class SimulateLoanController < AuthenticatedController
  def index
    @loan = Loan.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def loan_calculation loan
    prev = ((1.0 + loan.monthly_rate) ** loan.installments)
    result = loan.amount * (( prev * loan.monthly_rate)/( prev - 1))
    number_with_precision(result, precision: 3)
  end
  def loan_calculation_per_applicant(loan)
    result = loan_calculation(loan).to_f / loan.loan_applicants.count
    number_with_precision(result, precision: 3)
  end
  def formated_loan_amount(loan)
    number_with_precision(loan.amount, precision: 3)
  end
end

app/views/home/index.html.erb
<div id="home" class="cont">
  <div class="cont-welc">
    <div class="welc-text">
      <h1>Olá, somo a Nexoos</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam efficitur euismod lacinia. Ut urna ipsum,
        pharetra at semper sed, pellentesque eu neque. Pellentesque suscipit, nisl a eleifend volutpat, dui purus
        faucibus turpis, non mollis arcu ante quis eros. Donec semper tortor ut neque pellentesque, sit amet ultrices
        lectus porttitor.</p>
        <%= link_to 'Quero o meu emprestimo', new_user_registration_path, class:"btn btn-light"%>
    </div>
    <div class="welc-img"></div>
  </div>
  <div>
    <div class="cont-value">
      <div class="value-img"></div>
      <div class="value-text">
        <h1>Lorem ipsum dolor sit amet</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam efficitur euismod lacinia. Ut urna ipsum,
          pharetra at semper sed, pellentesque eu neque. Pellentesque suscipit, nisl a eleifend volutpat, dui purus
          faucibus turpis, non mollis arcu ante quis eros. Donec semper tortor ut neque pellentesque, sit amet ultrices
          lectus porttitor.</p>
          <%= link_to 'Quero o meu emprestimo', new_user_registration_path, class: "btn btn-primary"%>  
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NexoosChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NexoosChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="devise-cont">
      <div class="devise-form ">
        <%= yield %>
      </div>
      <div class="devise-img"></div>
    </div>
  </body>
</html>

app/views/loan/new.html.erb
<div id="loan" class="cont p-3">
  <h3>Nova solicitação de crédito</h3>
  <h6 class="pl-3 border-bottom"><i><b>Etapa</b> 1/2 </i></h6>
  <%= render 'preview' %>
  <%= render 'form' %>
</div>

app/views/loans/_form.html.erb
<div class="loan-form">
  <%= form_with do |f| %>
    <label for="">Valor do Emprestimo</label>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text">R$</span>
      </div>
      <%= f.number_field :amount, class:"form-control" %>
      <div class="input-group-append">
        <span class="input-group-text">.00</span>
      </div>
    </div>
    <div class="form-group">
      <label for="">Taxa <small> %a.m.</small></label>
      <%= f.text_field :monthly_rate, class:"form-control", disabled: true, value:(@loan.monthly_rate*100 )%>
    </div>
    <div class="form-group">
      <label for="">Numero de parcelas</label>
      <%= f.select :installments,(1..60).map{|n| n}, {}, {class:"custom-select"}%>
    </div>
  <%end%>
  <%= link_to 'Proxima etapa', new_loan_applicant_path, class:"btn btn-primary disabled", id:"next-step" %>
</div>

app/views/loans/index.html.erb
<div class="cont p-3" id="loan-show">
  <h2> Solicitações de crédito</h2>
  <% @loans.each do |loan|%>
    <%= render '/shared/loan/loan_card', loan: loan %>
  <% end %>
</div>

app/views/loans/new.html.erb
<div id="loan" class="cont p-3">
  <h3>Nova solicitação de crédito</h3>
  <h6 class="pl-3 border-bottom"><i><b>Etapa</b> 1/2 </i></h6>
  <%= render '/shared/loan/preview', loan: @loan %>
  <%= render 'form'%>
</div>

app/views/loans/show.html.erb
<div id="loan" class="cont p-3">
  <h3>Solicitação de crédito</h3>
    <%= render '/shared/loan/loan_card', loan: @loan %>
  <h5>Solicitacitantes</h5>

  <% @loan.loan_applicants.each do |la|%>
    <div class="p-1">
      <%= render '/shared/loan_applicant/loan_applicant_card', loan_applicant: la %>
    </div>
  <% end %>
</div>

app/views/painel/index.html.erb
<div class="cont">
  <div class="cont-navig">
    <div class="bnt-new-loan">
      <a href="<%= new_loan_path %>">
          <%= image_tag 'painel/Bitcoin P2P-rafiki.svg' %>
          <span> Solicitação de Crédito </span>
      </a>
    </div>
    <div class="bnt-new-simul">
      <a href="<%= simulate_loan_index_path %>">
        <div>
          <div>
            <%= image_tag 'painel/Analytics-pana.svg' %>
          </div>
          <span> Simular Crédito </span>
        </div>
      </a>
    </div>
  </div>
  <div class="loans-cont p-3">
    <h5>Ultimas Solicitações de crédito</h5>
    <div class="scroll-list" id='loans-list'>
      <% @loans.each do |loan|%>
        <%= render '/shared/loan/loan_card', loan: loan %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header id="header" class="p-2">
  <% if  current_user  %>
    <%= render '/shared/header/authenticated' %>
  <% elsif  devise_controller? %>
    <%= render '/shared/header/devise' %>
  <% elsif  "#{controller_name}" == 'home' %>
    <%= render '/shared/header/home' %>
  <%end%>
</header>

app/views/shared/header/_authenticated.html.erb
<div class="p-2">
  <%= link_to 'Painel', painel_index_path %>
</div>

<div class="dropdown p-2 border-left">
  <a class=" dropdown-toggle" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Solicitações de Crédito
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to 'Nova solicitação ', new_loan_path ,class:"dropdown-item"%>
    <%= link_to 'Todas Solicitações', loans_path ,class:"dropdown-item"%>
  </div>
</div>
<div class="dropdown p-2 border-left">
  <%= link_to 'Simular crédito', simulate_loan_index_path %>
</div>
<div class="p-2 border-left">
  <%= link_to 'Sair', destroy_user_session_path , method: :delete%>
</div>

app/views/shared/header/_devise.html.erb
<div class="p-2">
  <%= link_to 'Home', root_path%>  
</div>

app/views/shared/header/_home.html.erb
<div class="p-2">
  <%= link_to 'Cadastrar-se', new_user_registration_path%>
</div>
<div class="p-2 border-left">
  <%= link_to 'Acessar',user_session_path  %>
</div>

app/views/shared/loan/_loan_card.html.erb
<a href="<%= loan_path(loan.id) %>">
  <div class="p-1">
    <div class="card">
      <div class="d-flex flex-wrap">
        <div class="p-2">
          <span>Id </span>
          <p><span><%="#{loan.id}" %></span></p>
        </div>
        <div class="p-2">
          <span>Valor solicitado </span>
          <p>R$<span id="amount-prev" class="ml-2"><%= loan.amount ? "#{formated_loan_amount(loan)}" : '00' %></span></p>
        </div>
        <div class="p-2">
          <span>Numero de parcelas </span>
          <p><span id="installments-prev"><%= loan.installments ? "#{loan.installments}" : '00' %></span></p>
        </div>
        <div class="p-2">
          <span>Data de aquisição </span>
          <p><span id="installments-prev"><%= loan.date_acquisition.strftime("%d/%m/%Y") %></span></p>
        </div>
        <div class="p-2">
          <span>Taxa <small> %a.m.</small> </span>
          <p><span id="installments-prev"> <%= "#{loan.monthly_rate*100}"%>% </span></p>
        </div>
        <div class="p-2">
          <span>Valor parcelado mensal </span>
            <p>R$<span class="ml-2"><%= loan_calculation(loan) %></span></p>  
        </div>
        <div class="p-2">
          <span> Numero de solicitantes </span>
          <p><span><%= loan.loan_applicants.count %></span></p>  
        </div>
      </div>
    </div>
  </div>
</a>

app/views/shared/loan/_loans_list.html.erb
<a href="<%= loan_path(loan.id) %>">
  <div class="p-1">
    <div class="card">
      <div class="d-flex flex-wrap">
        <div class="p-2">
          <span>Id </span>
          <p><span><%="#{loan.id}" %></span></p>
        </div>
        <div class="p-2">
          <span>Valor solicitado </span>
          <p>R$<span id="amount-prev" class="ml-2"><%= loan.amount ? "#{formated_loan_amount(loan)}" : '00' %></span></p>
        </div>
        <div class="p-2">
          <span>Numero de parcelas </span>
          <p><span id="installments-prev"><%= loan.installments ? "#{loan.installments}" : '00' %></span></p>
        </div>
        <div class="p-2">
          <span>Data de aquisição </span>
          <p><span id="installments-prev"><%= loan.date_acquisition.strftime("%d/%m/%Y") %></span></p>
        </div>
        <div class="p-2">
          <span>Taxa <small> %a.m.</small> </span>
          <p><span id="installments-prev"> <%= "#{loan.monthly_rate*100}"%>% </span></p>
        </div>
        <div class="p-2">
          <span>Valor parcelado mensal </span>
            <p>R$<span class="ml-2"><%= loan_calculation(loan) %></span></p>  
        </div>
        <div class="p-2">
          <span> Numero de solicitantes </span>
          <p><span><%= loan.loan_applicants.count %></span></p>  
        </div>
      </div>
    </div>
  </div>
</a>

app/views/shared/loan/_preview.html.erb
<div class="loan-preview">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs" role="tablist">
        <li class="nav-item">
          <a class="nav-link <%= " active" if(controller_name == 'loans' || controller_name == 'simulate_loan') %> " id="loan-registration-nav"
            data-toggle="list" href="#loan-registration-prev" role="tab" aria-controls="home">Cadastro de solicitação de
            crédito</a>
        </li>
        <% if controller_name != 'simulate_loan'%>
          <li class="nav-item">
            <a class="nav-link <%= (controller_name == 'loan_applicants')? 'active': 'disabled' %>" id="loan-applicant-nav"
              data-toggle="list" href="#loan-applicant-prev" role="tab" aria-controls="profile">Cadastro de
              solicitante</a>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade <%= "show active" if(controller_name == 'loans' || controller_name == 'simulate_loan') %>" id="loan-registration-prev"
          role="tabpanel" aria-labelledby="loan-registration-nav">
          <div>
            <span>Valor solicitado </span>
            <p>R$<span id="amount-prev" class="ml-2">
                <%= loan.amount ? "#{formated_loan_amount(loan)}" : '00' %>
              </span></p>
          </div>
          <div>
            <span>Numero de parcelas </span>
            <p><span id="installments-prev">
                <%= loan.installments ? "#{loan.installments}" : '00' %>
              </span></p>
          </div>
          <div>
            <span>Taxa <small> %a.m.</small> </span>
            <p><span id="installments-prev"> <%= "#{loan.monthly_rate*100}"%>% </span></p>
          </div>
          <div>
            <span>Valor parcelado mensal </span>
            <% if loan.amount && loan.installments%>
              <p>R$<span class="ml-2">
              <%= loan_calculation(loan) %>
              </span></p>  
            <% else %>
              <p>R$<span id="installments-monthly-prev" class="ml-2">00</span></p>
            <% end %>
          </div>
          <%if controller_name == 'loan_applicants' || controller_name == 'simulate_loan' %>
            <div>
              <span> Numero de solicitantes </span>
              <% if loan.loan_applicants.count > 0 %>
                <p><span>
                <%= loan.loan_applicants.count %>
                </span></p>  
              <% else %>
                <p><span id="number-of-applicants-prev">00</span></p>
              <% end %>
            </div>
             <div>
              <span> Valor da parcela por solicitante </span>
              <% if loan.loan_applicants.count > 0 %>
                <p>R$<span class="ml-2">
                <%= loan_calculation_per_applicant(loan) %>
                </span></p>  
              <% else %>
                <p>R$<span id="installments-per-applicants-prev" class="ml-2">00</span></p>
              <% end %>
            </div>
          <% end%>
        </div>
        <div class="tab-pane fade <%= "show active" if(controller_name == 'loan_applicants') %>" id="loan-applicant-prev" role="tabpanel" aria-labelledby="loan-applicant-nav">
          <div>
            <span>Razão social </span>
            <p><span id="company-name-prev" class="ml-2"></span></p>
          </div>
          <div>
            <span>CNPJ </span>
            <p><span id="cnpj-prev" class="ml-2"></span></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/loan_applicant/_loan_applicant_card.html.erb
<div class="loan-preview">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="loan-applicant-nav-<%="#{loan_applicant.id}"%>"
            data-toggle="list" href="#loan-applicant-prev-<%="#{loan_applicant.id}"%>" role="tab" aria-controls="applicant-<%="#{loan_applicant.id}" %>"> Solicitante</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " id="addresses-nav-<%="#{loan_applicant.id}"%>"
            data-toggle="list" href="#addresses-prev-<%="#{loan_applicant.id}"%>" role="tab" aria-controls="addresses-<%="#{loan_applicant.id}" %>">Endereços</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " id="loan-installments-nav-<%="#{loan_applicant.id}"%>"
            data-toggle="list" href="#loan-installments-prev-<%="#{loan_applicant.id}"%>" role="tab" aria-controls="installments-<%="#{loan_applicant.id}" %>">Parcelas</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="loan-applicant-prev-<%="#{loan_applicant.id}"%>"
          role="tabpanel" aria-labelledby="loan-applicant-nav-<%="#{loan_applicant.id}"%>">
          <div class="d-flex flex-wrap">
            <div class="p-2">
              <span>Id </span>
              <p><span><%="#{loan_applicant.id}" %></span></p>
            </div>
            <div class="p-2">
              <span>Razão social </span>
              <p><span class="ml-2"><%="#{loan_applicant.company_name}" %></span></p>
            </div>
            <div class="p-2">
              <span>CNPJ </span>
              <p><span class="ml-2"><%="#{loan_applicant.cnpj}" %></span></p>
            </div>
            <div class="p-2">
              <span>Telefones </span>
              <p><span class="ml-2"><%="#{loan_applicant.phones.join(', ')}" %></span></p>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="addresses-prev-<%="#{loan_applicant.id}"%>" role="tabpanel" aria-labelledby="addresses-nav-<%="#{loan_applicant.id}"%>">
          <% loan_applicant.addresses.each do |address| %>
            <div class="p-1">
              <div class="border">
                <div class="d-flex flex-wrap">
                  <div class="p-2">
                    <span>Cep </span>
                    <p><span><%="#{address.zip_code}" %></span></p>
                  </div>
                  <div class="p-2">
                    <span>Estado </span>
                    <p><span><%="#{address.state}" %></span></p>
                  </div>
                  <div class="p-2">
                    <span>Cidade </span>
                    <p><span><%="#{address.city}" %></span></p>
                  </div>
                  <div class="p-2">
                    <span>Rua </span>
                    <p><span><%="#{address.street}" %></span></p>
                  </div>
                  <div class="p-2">
                    <span>Número </span>
                    <p><span><%= (address.number.empty?) ? "s/n" : "#{address.number}"  %></span></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="tab-pane fade" id="loan-installments-prev-<%="#{loan_applicant.id}"%>" role="tabpanel" aria-labelledby="loan-installments-nav-<%="#{loan_applicant.id}"%>" >
          <% loan_applicant.loan_installments.each do |loan_installment| %>
            <div class="p-1">
              <div class="border">
                <div class="d-flex flex-wrap">
                  <div class="p-2">
                    <span>Numero da parcela </span>
                    <p><span><%="#{loan_installment.installment_number}" %></span></p>
                  </div>
                  <div class="p-2">
                    <span>Valor da parcela </span>
                    <p>R$<span><%="#{loan_installment.value}" %></span></p>
                  </div>
                  <div class="p-2">
                    <span>Data de entrega </span>
                    <p><span><%="#{loan_installment.due_date.strftime("%d/%m/%Y")}"%></span></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/simulate_loan/_form.html.erb
<div class="loan-simulate-form">
  <%= form_with do |f| %>
    <label for="">Valor do Emprestimo</label>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text">R$</span>
      </div>
      <%= f.number_field :amount, class:"form-control" %>
      <div class="input-group-append">
        <span class="input-group-text">.00</span>
      </div>
    </div>
    <div class="form-group">
      <label for="">Taxa <small> %a.m.</small></label>
      <%= f.text_field :monthly_rate, class:"form-control", disabled: true, value:(@loan.monthly_rate*100 )%>
    </div>
    <div class="form-group">
      <label for="">Numero de parcelas</label>
      <%= f.select :installments,(1..60).map{|n| n}, {}, {class:"custom-select"}%>
    </div>
    <div class="form-group">
      <label for="">Numero de solicitantes</label>
      <%= f.select :applicants,(1..200).map{|n| n}, {}, {class:"custom-select"}%>
    </div>
  <%end%>
</div>

app/views/simulate_loan/index.html.erb
<div id="loan" class="cont p-3">
  <h3>Simulação de crédito</h3>
  <%= render '/shared/loan/preview', loan: @loan %>
  <%= render 'form'%>
</div>